export const images = {
  logo: '/images/logo.png',
  labamboche: '/images/labamboche.jpg',
  profile: '/images/profile.svg',
  cart: '/images/cart.svg',
  cake_rose: '/images/cake_rose.png',
  fruit_tart: '/images/fruit_tart.jpg',
  // labamche: '/images/labamche.jpg',
  // logo: '/images/logo.png',
  pastry: '/images/pastry.jpg',
  pastry_1: '/images/pastry_1.jpg',
  pastry_2: '/images/pastry_2.jpg',
  pastry_3: '/images/pastry_3.jpg',
  pizza: '/images/pizza.jpg',
  reservation: '/images/reservation.jpg',
  restaurant: '/images/restaurant.jpg',
  beverage_1: '/images/beverage_1.jpg',
  beverage: '/images/beverage.jpg',
  cake_2: '/images/cake_2.jpg',
  cake_1: '/images/cake_1.jpg',
  cookies: '/images/cookies.jpg',
  cookies_1: '/images/cookies_1.jpg',
  croissant_1: '/images/croissant_1.jpg',
  croissant_2: '/images/croissant_2.jpg',
  fruit_tart: '/images/fruit_tart.jpg',
  jam_1: '/images/jam_1.jpg',
  macarons: '/images/macarons.jpg',
  pastry_puff: '/images/pastry_puff.jpg',
  scone: '/images/scone.png',
  tart: '/images/tart.jpg',
  barley_soup: '/images/barley_soup.jpg',
  sandwich: '/images/sandwich.jpg',
  quiche: '/images/quiche.jpg',
  pasta: '/images/pasta.jpg',
  pasta_1: '/images/pasta_1.webp',
  muffins: '/images/muffins.jpg',
  cupcake: '/images/cupcake.jpg',
  hero_image: '/images/hero_image.png',
  pizza_1: '/images/pizza_1.png',
  chocolate: '/images/chocolate.jpg',
  croissant: '/images/croissant.png',
  pastries: '/images/pastries.png',
  shop: '/images/shop.jpg',
  bakery: '/images/bakery.jpg',
  bakery_1: '/images/bakery_1.jpg',
  bakery_2: '/images/bakery_2.jpg',
  bakery_3: '/images/bakery_3.jpg',
  bakery_bread: '/images/bakery_bread.jpg',
  delivery: '/images/delivery.png',
  chef: '/images/chef.png',
  restaurantjpeg: '/images/restaurantjpeg.jpeg',
  location: '/images/location.svg',
  email: '/images/email.svg',
  phone: '/images/phone.svg',
  time: '/images/time.svg',
  instagram: '/images/instagram.svg',
  bakerysetup: '/images/bakerysetup.jpg',
  cakeandmacarons: '/images/cakeandmacarons.jpg',
  after_dark: '/images/after_dark.png',
  afterdark: '/images/afterdark.png',
  day_restaurant: '/images/day_restaurant.jpg',
  restaurant_space: '/images/restaurant_space.jpg',
  restaurant_image: '/images/restaurant_image.jpg',
  tea_woman: '/images/tea_woman.svg',
  spring_image: '/images/spring_image.svg',
  lamination_image: '/images/lamination_image.svg',
  pastry_chef: '/images/pastry_chef.png',
  master_boulanger: '/images/master_boulanger.png',
  head_chocolatier: '/images/head_chocolatier.png',
  creative_director: '/images/creative_director.png',
  reservation_image: '/images/reservation_image.png',
  timing_policy: '/images/timing_policy.svg',
  menu_notice: '/images/menu_notice.svg',
  calendar: '/images/calendar.svg',
  time_icon: '/images/time_icon.svg',
  party_size: '/images/party_size.svg',
  delete_icon: '/images/delete_icon.svg',
  profile_image: '/images/profile_image.png',

  cakes: '/new-images/cakes.svg',
  cookies: '/new-images/cookies.svg',
  crossiant: '/new-images/crossiant.svg',
  gradient_bg: '/new-images/gradient_bg.svg',
  scone_bread: '/new-images/scone_bread.svg',
  pasta: '/new-images/pasta.svg',
  cupcakes: '/new-images/cupcakes.svg',
  cookies_gradient: './new-images/cookies_gradient.svg',
  sandwish: '/new-images/sandwish.svg',
  background: '/new-images/background.svg',
};
export const menuList = [
  {
    id:1,
    name:'cakes and macaroons'
  },
  {
    id:2,
    name:'Cookies and Tart'
  },
  {
    id:3,
    name:'croissants and pastries'
  },
  {
    id:4,
    name:'jam, honey and beverages'
  },
  {
    id:5,
    name:'pasta, quiches, soups and sandwishes'
  },
  {
    id:6,
    name: 'scones, muffins and bread'
  }
]
export const listMenu = [
  {
    id: 1,
    name: 'cookies and tart',
    img: images.cookies,
  },
  {
    id: 2,
    name: 'cakes ',
    img: images.cakes,
  },
  {
    id: 3,
    name: 'crossiant',
    img: images.crossiant,
  },
  {
    id: 4,
    name: 'scone',
    img: images.gradient_bg,
  },
  {
    id: 5,
    name: 'cupcake',
    img: images.cupcakes,
  },
  {
    id: 6,
    name: 'pasta',
    img: images.pasta,
  },
  {
    id: 7,
    name: 'scone bread',
    img: images.scone_bread,
  },
  {
    id: 8,
    img: images.sandwish,
    name: 'sandwish',
  },
];
export const bakeryList = [
  {
    id: 1,
    img: images.bakery_bread,
    name: 'bakery bread',
  },
  { id: 2, img: images.bakery, name: 'bakery hall' },
];

export const mostPopular = [
  {
    id: '1',
    name: 'Decaf Espresso',
    price: '20',
    image: images.beverage,
    description: 'Smooth, low-acid decaf.',
  },
  {
    id: '2',
    name: 'strawberry jam',
    price: '40',
    image: images.jam_1,
    description: 'House-made strawberry jam.',
  },
  {
    id: '3',
    name: 'sandwich',
    price: '50',
    image: images.sandwich,
    description: 'Toasted sandwich .',
  },
  {
    id: '4',
    name: 'cupcake',
    price: '45',
    image: images.cupcake,
    description: 'Moist cupcake .',
  },
  {
    id: '5',
    name: 'cupcake',
    price: '45',
    image: images.cupcake,
    description: 'Moist cupcake .',
  },
  {
    id: '6',
    name: 'cupcake',
    price: '45',
    image: images.cupcake,
    description: 'Moist cupcake .',
  },
];
// export const blogList = [
//   {
//     id: 1,
//     image: images.restaurantjpeg,
//     title: 'Grand Opening: La Bamboche Leslieville!',
//     post: "We're thrilled to open our second location at 892 Queen St E with an updated menu, cocktail brunch, and all your favorite Japanese-French pastries.",
//     date: 'Dec 15, 2025',
//   },
//   {
//     id: 2,
//     image: images.pastry,
//     title: 'Winter Seasonal Specials Are Here',
//     post: 'Warm up with our new yuzu citrus tarts, matcha chestnut cakes, and limited-edition holiday macarons available now at both locations.',
//     date: 'Jan 02, 2026',
//   },
//   {
//     id: 3,
//     image: images.restaurant,
//     title: 'La Bamboche After Dark Returns',
//     post: 'Join us for evening events with wine pairings, dessert tastings, and live music. Reservations required — call your nearest location!',
//     date: 'Jan 02, 2026',
//   },
// ];
export const productsList = [
  {
    id: '1',
    name: 'carrot cake',
    price: '20',
    image: images.cupcake,
    description: 'Moist cupcake topped with creamy buttercream.',
    category: 'cake and macarons',
  },
  {
    id: '2',
    name: 'almond florentine',
    price: '40',
    image: images.cookies_1,
    description: 'House-made strawberry jam bright, fresh, and spreadable.',
    category: 'cookies and tarts',
  },
  {
    id: '3',
    name: 'Butter Croissant',
    price: '50',
    image: images.sandwich,
    description: 'Toasted sandwich with fresh greens and savory filling.',
    category: 'croissants and pastries',
  },
  {
    id: '4',
    name: 'cupcake',
    price: '45',
    image: images.cupcake,
    description: 'Moist cupcake topped with creamy buttercream.',
    category: 'cakes and macarons',
  },
  {
    id: '5',
    name: 'croissant',
    price: '30',
    image: images.croissant_2,
    description: 'Flaky French croissant, buttery and golden brown.',
    category: 'pastries and croissants',
  },
  {
    id: '6',
    name: 'banana pudding',
    price: '55',
    image: images.tart,
    description: 'Fresh fruit tart with creamy custard filling.',
    category: 'cookies and tarts',
  },
  {
    id: '7',
    name: 'carrot cake',
    price: '20',
    image: images.cupcake,
    description: 'Moist cupcake topped with creamy buttercream.',
    category: 'cakes and macarons',
  },
  {
    id: '8',
    name: 'almond florentine',
    price: '40',
    image: images.cookies_1,
    description: 'House-made strawberry jam bright, fresh, and spreadable.',
    category: 'cookies and tarts',
  },
  {
    id: '9',
    name: 'Butter Croissant',
    price: '50',
    image: images.sandwich,
    description: 'Toasted sandwich with fresh greens and savory filling.',
    category: 'croissants and pastries',
  },
  {
    id: '10',
    name: 'cupcake',
    price: '45',
    image: images.cupcake,
    description: 'Moist cupcake topped with creamy buttercream.',
    category: 'cakes and macarons',
  },
  {
    id: '11',
    name: 'croissant',
    price: '30',
    image: images.croissant_1,
    description: 'Flaky French croissant, buttery and golden brown.',
    category: 'pastries and croissants',
  },
  {
    id: '12',
    name: 'banana pudding',
    price: '55',
    image: images.tart,
    description: 'Fresh fruit tart with creamy custard filling.',
    category: 'cookies and tarts',
  },

  {
    id: '13',
    name: 'Decaf Espresso',
    price: '20',
    image: images.beverage,
    description: 'Smooth, low-acid decaf espresso with chocolatey notes.',
    category: 'jams, beverages and honey',
  },
  {
    id: '14',
    name: 'strawberry jam',
    price: '40',
    image: images.jam_1,
    description: 'House-made strawberry jam bright, fresh, and spreadable.',
    category: 'jams, beverages and honey',
  },
  {
    id: '15',
    name: 'sandwich',
    price: '50',
    image: images.sandwich,
    description: 'Toasted sandwich with fresh greens and savory filling.',
    category: 'soups, sandwiches, pasta and quiches ',
  },
  {
    id: '16',
    name: 'cupcake',
    price: '45',
    image: images.cupcake,
    description: 'Moist cupcake topped with creamy buttercream.',
    category: 'scones, muffins and bread',
  },
  {
    id: '17',
    name: 'croissant',
    price: '30',
    image: images.croissant_2,
    description: 'Flaky French croissant, buttery and golden brown.',
    category: 'soups, sandwiches, pasta and quiches ',
  },
  {
    id: '18',
    name: 'fruit tart',
    price: '55',
    image: images.tart,
    description: 'Fresh fruit tart with creamy custard filling.',
    category: 'scones, muffins and bread',
  },
  {
    id: '19',
    name: 'Decaf Espresso',
    price: '20',
    image: images.beverage,
    description: 'Smooth, low-acid decaf espresso with chocolatey notes.',
    category: 'jams, beverages and honey',
  },
  {
    id: '20',
    name: 'strawberry jam',
    price: '40',
    image: images.jam_1,
    description: 'House-made strawberry jam bright, fresh, and spreadable.',
    category: 'jams, beverages and honey',
  },
  {
    id: '21',
    name: 'sandwich',
    price: '50',
    image: images.sandwich,
    description: 'Toasted sandwich with fresh greens and savory filling.',
    category: ' sandwiches and quiches ',
  },
  {
    id: '22',
    name: 'cupcake',
    price: '45',
    image: images.cupcake,
    description: 'Moist cupcake topped with creamy buttercream.',
    category: 'scones, muffins and bread',
  },
  {
    id: '23',
    name: 'croissant',
    price: '30',
    image: images.croissant_1,
    description: 'Flaky French croissant, buttery and golden brown.',
    category: 'soups and pasta ',
  },
  {
    id: '24',
    name: 'fruit tart',
    price: '55',
    image: images.tart,
    description: 'Fresh fruit tart with creamy custard filling.',
    category: 'scones, muffins and bread',
  },
];
export const categoriesList = [
  { id: 1, name: 'All' },
  { id: 2, name: 'cakes and macarons' },
  { id: 3, name: 'cookies and tarts' },
  { id: 4, name: 'croissants and pastries' },
  { id: 5, name: 'jams, beverages and honey' },
  { id: 6, name: ' sandwiches and quiches ' },
  { id: 7, name: 'scones, muffins and bread' },
  { id: 8, name: 'soups and pasta' },
];

export const restaurantList = [
  { id: 1, name: 'restaurant image', image: images.restaurantjpeg },
  { id: 2, name: 'shop image', image: images.shop },
  { id: 3, name: 'restaurant', image: images.reservation },
  { id: 4, name: 'restaurant image', image: images.restaurant },
];

export const blogList = [
  {
    id: 1,
    image: images.lamination_image,
    sub_title: 'process',
    title: 'The art of 72 hour lamination',
    post: 'Discover the secret behind our signature airy,honeycombed layers.',
    date: 'Dec 15, 2025',
  },

  {
    id: 2,
    image: images.spring_image,
    sub_title: 'events',
    title: 'A spring morning in the garden',
    post: 'Higlighting our seasonal collaboration with local florists, featuring floral-inspired pastries and teas.',
    date: 'Jan 02, 2026',
  },
  {
    id: 3,
    image: images.tea_woman,
    sub_title: 'community',
    title: 'Our newest atelier in Leslieville',
    post: 'Tracing our journey from a single shop to a beloved neighborhood bakery, and our vision for the future.',
    date: 'Jan 02, 2026',
  },
];

export const artisanList = [
  {
    id: 1,
    image: images.pastry_chef,
    name: 'chef julien mercier',
    position: 'executive pastry chef',
  },
  {
    id: 2,
    image: images.head_chocolatier,
    name: 'sophie laurent',
    position: 'head chocolatier',
  },
  {
    id: 3,
    image: images.master_boulanger,
    name: 'marcus chen',
    position: 'master boulanger',
  },
  {
    id: 4,
    image: images.creative_director,
    name: 'elena rosi',
    position: 'creative director',
  },
];

export const suggestionList = [
  {

  }
]
