import Footer from './_components/Footer/Footer';
import Header from './_components/Header';
import './_styles/globals.css';
import localFont from 'next/font/local';
import 'boxicons/css/boxicons.min.css';

export const metadata = {
  title: 'La Bamboche',
  description: 'Generated by create next app',
};
const notoRegular = localFont({
  src: './_font/NotoSerif-regular.woff2',
  variable: '--font-noto-regular',
  style: 'normal',
});

const notoBold = localFont({
  src: './_font/NotoSerif-bold.woff2',
  variable: '--font-noto-bold',
  style: 'normal',
});
const liberationRegular = localFont({
  src: './_font/LiberationSerif-Regular.woff2',
  variable: '--font-liberation-regular',
  style: 'normal',
});

const liberationBold = localFont({
  src: './_font/LiberationSerif-Bold.woff2',
  variable: '--font-liberation-bold',
  style: 'normal',
});
const vietnamProRegular = localFont({
  src: './_font/BeVietnamPro-Regular.ttf',
  variable: '--font-vietnam-regular',
  style: 'normal',
});
const vietnamProSemiBold = localFont({
  src: './_font/BeVietnamPro-SemiBold.woff2',
  variable: '--font-vietnam-pro-semi-bold',
  style: 'normal',
});
const vietnamProExtraLight = localFont({
  src: './_font/BeVietnamPro-ExtraLight.woff2',
  variable: '--font-vietnam-Extra-Light',
  style: 'normal',
});
const vietnamProLight = localFont({
  src: './_font/BeVietnamPro-Light.woff2',
  variable: '--font-vietnam-Light',
  style: 'normal',
});
export default function RootLayout({ children }) {
  return (
    <html lang='en' className=''>
      <body
        className={`${notoRegular.variable} ${notoBold.variable} ${liberationRegular.variable} ${liberationBold.variable}${vietnamProSemiBold.variable}
        ${vietnamProExtraLight.variable} ${vietnamProLight.variable} ${vietnamProRegular.variable} `}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
